# Generated by Django 2.2.6 on 2019-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('plantaoPadrao', models.CharField(choices=[('Madrugada', 'Madrugada'), ('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=15)),
                ('folfer', models.CharField(choices=[('Feirista', 'Feirista'), ('Folguista', 'Folguista')], max_length=10)),
            ],
        ),
    ]
