# Generated by Django 2.2.6 on 2019-11-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='folfer',
            field=models.CharField(choices=[('Fei', 'Feirista'), ('Fol', 'Folguista')], max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plantaoPadrao',
            field=models.CharField(choices=[('Mad', 'Madrugada'), ('Man', 'Manhã'), ('Tar', 'Tarde'), ('Noi', 'Noite')], max_length=15),
        ),
    ]
