# Generated by Django 2.2.7 on 2019-11-17 17:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20191116_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='folfer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fei', 'Feirista'), ('Fol', 'Folguista')], max_length=7),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plantaoPadrao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mad', 'Madrugada'), ('Man', 'Manhã'), ('Tar', 'Tarde'), ('Noi', 'Noite')], max_length=15),
        ),
    ]
