# Generated by Django 2.2.7 on 2019-11-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20191117_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='folfer',
            new_name='folga_ferias',
        ),
    ]
