# Generated by Django 2.2.7 on 2019-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_auto_20191117_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='folga_ferias',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ferista',
            field=models.BooleanField(default=False, verbose_name='Feirista'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='folguista',
            field=models.BooleanField(default=False, verbose_name='Folguista'),
        ),
    ]
