# Generated by Django 2.2.7 on 2019-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20191117_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ferista',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='feirista',
            field=models.BooleanField(default=False, verbose_name='feirista'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='folguista',
            field=models.BooleanField(default=False, verbose_name='folguista'),
        ),
    ]
